### PR TITLE
Add mastodon link to footer

### LINKED ISSUE #131: Add link to other social acocunts if they are official
Namely the [Mastodon account](https://fosstodon.org/@napari), but there might be more. 

The account not 'verified' now because there is no link back on the docs page (which does link to other social resources like Twitter and Image.sc). For a 'verified' example see [PyTorch](https://social.lfx.dev/@pytorch).

### PR DESCRIPTION
**Pull request by melissawm**
Closes #131

### CODE REVIEW

**Comment by Czaki** [comment]
May links in the footer be part of `conf.py` in docs?

**Comment by melissawm** [comment]
I don't think so. Our footer is customized so that's not a pydata sphinx theme setting, I believe. But I can check

**Comment by jni** [comment]
When are the light blue and white fills used? Can I have a screenshot? 🙏

**Review by jni — APPROVED** [review]
(But anyway, thank you! 🙏)

**Comment by jni** [comment]
> The light blue version of the icons appears on hover:

wow, that is subtle. 🤣 I would suggest updating to the napari blue, but obviously that should come in a later PR. Thanks!

**Pull request merged**
