### PR TITLE
Remove PyData Sphinx Theme pin

### PR DESCRIPTION
**Pull request by melissawm**
Includes fixes for the primary sidebar compatible with PST 0.15.3

### CODE REVIEW

**Comment by melissawm** [comment]
That did not fix the nav bar decoration 😢 I'll come back to this tomorrow.

**Comment by psobolewskiPhD** [comment]
I re-ran CI since 15.3 has been released.
Looking at the artifact:
- https://github.com/napari/napari-sphinx-theme/issues/80 appears fixed 🎉 
- there is an annoying shift when mouse-over the top nav bar: when you mouse over the whole bar shifts up a few pixels 
- the black highlight bar is in a different spot
image
- left-hand-size ToC is missing:
image

**Comment by melissawm** [comment]
I think I got it, but we'll also need to update the docs, see https://github.com/napari/docs/pull/423

**Comment by psobolewskiPhD** [comment]
The nav bar looks fixed!
You rock!
image

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by melissawm** [comment]
With the latest commit to napari-docs this should be complete, including disabling the back-to-top button @jni 

Let me know if you see any other glaring issues before we upgrade

**Comment by psobolewskiPhD** [comment]
I'd be ok with optimistically merging and releasing and then we see how it builds over there.
Worst case there is some glitch in dev docs?

**Comment by melissawm** [comment]
There shouldn't be, but I'll be available to fix this weekend if that happens.

**Comment by psobolewskiPhD** [comment]
I have the Pacific meeting with Juan (and hopefully others!) this evening, so I'll bring this up then and maybe we can get it merged and released.
If we're really concerned we could release without this (because a few small fixes were merged) and then merge and release this in it's own release?

**Comment by melissawm** [comment]
Thats up to you, I don't necessarily see an advantage in releasing without this PR

**Comment by jni** [comment]
That's what I think. 😜

**Pull request merged**
