### PR TITLE
Fix footer display

### PR DESCRIPTION
**Pull request by melissawm**
I did not notice before, but the recent pydata sphinx theme versions had unset our footer. I will send a PR later to fix the 0.5.0 docs in napari.github.io, but this fixes the immediate issues and changes the wording on the footer items as requested in #12 .

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
What do you think of `Forum` for image.sc and `Ask a Q` for Zulip?
Seems more natural?
Also, I recall there being some opposition to "Chat" due to connotations with AI chatbots.

**Comment by melissawm** [comment]
We talked about it at the meeting and kinda decided on chat if I remember correctly? But yes, forum would be my first choice, I just followed the existing suggestions from the issue 😊

**Comment by psobolewskiPhD** [comment]
I'm ambivalent about the `chat` part, but rather strongly feel that image.sc should be labeled as forum.

**Comment by DragaDoncila** [comment]
I was the one with the concern about using `chat`, but I have actually revised that and am in favour as I think it's the option that makes most sense and is pretty unambiguous. 

It's also totally different to how most chat bots are shown, with the little bubble in the right hand corner that inevitably makes some Clippy-like remark about helping you out.

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
I don't mind "ask a q" vs "forum" for image.sc, so I'm not gonna press merge. Since Peter feels strongly about Forum *and* it's shorter, let's go with that. I'm happy we got consensus on chat. 😊

**Comment by melissawm** [comment]
Updated

**Pull request merged**
